name: Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta dashboard
        id: metadash
        uses: docker/metadata-action@v5
        with:
          images: babbartech/babbar-dashboard-api
      -
        name: Docker meta trafilatura
        id: metatra
        uses: docker/metadata-action@v5
        with:
          images: babbartech/trafilatura
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export dashboard to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/prod/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadash.outputs.tags }}
          labels: ${{ steps.metadash.outputs.labels }}
      -
        name: Build and export trafilatura to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/trafilatura/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metatra.outputs.tags }}
          labels: ${{ steps.metatra.outputs.labels }}
