name: Docker Hub

on:
  push:
    branches:
      - "main"
  create:
    tag

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Vérifier la branche ou le tag
        run: |
          if [ -n "$GITHUB_REF" ]; then
            if [[ "$GITHUB_REF" == refs/tags/* ]]; then
              export IMAGE_TAG=${GITHUB_REF#refs/tags/}
              echo "Create tag : $GITHUB_REF use tag $IMAGE_TAG"
            else
              echo "push on : $GITHUB_REF use tag latest"
              export IMAGE_TAG=latest
            fi
          else
            echo "No tag define"
            exit 1
          fi
        env:
          GITHUB_REF: ${{ github.ref }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export dashboard to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/prod/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: babbartech/babbar-dashboard-api:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
      -
        name: Build and export trafilatura to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/trafilatura/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: babbartech/trafilatura:$IMAGE_TAG
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
